version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: cd.go.plugin:go-plugin-api
    versions:
    - "> 19.1.0"
  - dependency-name: io.fabric8:kubernetes-client
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.2.1
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.8.0
